"""Staggered contour trench (SCT) siting and sizing, with the slope safety gate.

Geometry follows the brief: L 3-5 m, W 0.5 m, D <= 0.5 m, berm gap >= 2 m, section 0.25 m2.
The vertical interval (VI) between rows is derived by matching trench storage to the
runoff generated by the strip between rows, then clamped to practical limits.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

from .green_ampt import SoilParams, infiltration_rate


@dataclass(frozen=True)
class SlopePolicy:
    """Slope thresholds (percent). The brief gives a 15-33 % band; the exact cut-offs are a
    policy decision, so both are explicit parameters.

    <= review_above_pct              : excavation permitted
    review_above_pct .. bypass_above : excavation permitted only with engineer sign-off, depth capped
    > bypass_above_pct               : NO excavation - vegetative stabilisation only
    """
    review_above_pct: float = 15.0
    bypass_above_pct: float = 33.0
    restricted_depth_m: float = 0.30


@dataclass(frozen=True)
class TrenchGeometry:
    length_m: float = 4.0
    width_m: float = 0.5
    depth_m: float = 0.5
    berm_gap_m: float = 2.0

    def __post_init__(self):
        if not 3.0 <= self.length_m <= 5.0:
            raise ValueError("trench length must be 3-5 m")
        if self.width_m <= 0 or not 0 < self.depth_m <= 0.5:
            raise ValueError("width must be > 0 and depth in (0, 0.5] m")
        if self.berm_gap_m < 2.0:
            raise ValueError("berm gap must be >= 2 m")

    @property
    def section_m2(self) -> float:
        return self.width_m * self.depth_m

    @property
    def volume_m3(self) -> float:
        return self.section_m2 * self.length_m

    @property
    def wetted_area_m2(self) -> float:
        """Base + two long sides + two ends (worst-case, full trench)."""
        return (self.length_m * self.width_m
                + 2 * self.length_m * self.depth_m
                + 2 * self.width_m * self.depth_m)

    @property
    def storage_per_contour_m(self) -> float:
        """Storage per metre of contour length, averaged over trench + berm gap (m3/m)."""
        return self.volume_m3 / (self.length_m + self.berm_gap_m)


@dataclass
class TrenchPlan:
    action: str                 # "excavate" | "excavate_restricted" | "vegetative_only"
    geometry: TrenchGeometry | None
    vertical_interval_m: float | None = None
    horizontal_spacing_m: float | None = None
    rows: int = 0
    trenches_per_row: int = 0
    total_trenches: int = 0
    total_excavation_m3: float = 0.0
    total_storage_m3: float = 0.0
    drain_time_h: float | None = None
    notes: list[str] = field(default_factory=list)
    requires_engineer_review: bool = False


def runoff_depth_m(design_rain_mm: float, runoff_coeff: float) -> float:
    if design_rain_mm < 0 or not 0 <= runoff_coeff <= 1:
        raise ValueError("design_rain_mm >= 0 and runoff_coeff in [0,1] required")
    return design_rain_mm / 1000.0 * runoff_coeff


def vertical_interval(slope_pct: float, geometry: TrenchGeometry, design_rain_mm: float,
                      runoff_coeff: float, vi_min_m: float = 0.5, vi_max_m: float = 3.0) -> tuple[float, float]:
    """Return (VI, horizontal spacing) in metres.

    Storage balance per metre of contour:  storage_per_contour = R * HD,
    where R is runoff depth and HD the horizontal distance between rows; VI = HD * slope.
    Steeper slope or heavier runoff -> smaller HD -> more rows.
    """
    if slope_pct <= 0:
        raise ValueError("slope_pct must be > 0")
    s = slope_pct / 100.0
    R = runoff_depth_m(design_rain_mm, runoff_coeff)
    hd = geometry.storage_per_contour_m / R if R > 0 else float("inf")
    vi = min(max(hd * s, vi_min_m), vi_max_m)
    return vi, vi / s


def drain_time_h(geometry: TrenchGeometry, soil: SoilParams) -> float:
    """Time to drain a full trench, using the Green-Ampt rate at a representative cumulative depth.

    Conservative: uses F = trench depth (cm) as the representative wetting depth.
    """
    F_cm = geometry.depth_m * 100.0
    rate_m_h = infiltration_rate(F_cm, soil) / 100.0
    return geometry.volume_m3 / (rate_m_h * geometry.wetted_area_m2)


def plan_trenches(slope_pct: float, area_ha: float, soil: SoilParams, design_rain_mm: float = 100.0,
                  runoff_coeff: float = 0.3, geometry: TrenchGeometry | None = None,
                  policy: SlopePolicy = SlopePolicy(), max_drain_h: float = 48.0) -> TrenchPlan:
    """Plan trenches for one treatment polygon of given mean slope and area."""
    if area_ha <= 0:
        raise ValueError("area_ha must be > 0")
    if slope_pct < 0:
        raise ValueError("slope_pct must be >= 0")
    geometry = geometry or TrenchGeometry()
    notes: list[str] = []

    if slope_pct > policy.bypass_above_pct:
        return TrenchPlan("vegetative_only", None, notes=[
            f"Slope {slope_pct:.1f}% > {policy.bypass_above_pct:.0f}%: excavation bypassed. "
            "Prescribe vegetative stabilisation (contour vegetative barriers, grass/shrub planting)."])

    action, review = "excavate", False
    if slope_pct > policy.review_above_pct:
        action, review = "excavate_restricted", True
        geometry = TrenchGeometry(geometry.length_m, geometry.width_m,
                                  min(geometry.depth_m, policy.restricted_depth_m), geometry.berm_gap_m)
        notes.append(f"Slope {slope_pct:.1f}% in restricted band: depth capped at "
                     f"{geometry.depth_m:.2f} m, engineer sign-off required.")

    s_eff = max(slope_pct, 1.0)  # near-flat land: use 1% so spacing stays finite
    vi, hd = vertical_interval(s_eff, geometry, design_rain_mm, runoff_coeff)
    area_m2 = area_ha * 10_000.0
    # Rows spaced by HD; each row occupies (HD x row length). Assume a square treatment polygon.
    side = math.sqrt(area_m2)
    rows = max(int(side // hd), 1)
    per_row = max(int(side // (geometry.length_m + geometry.berm_gap_m)), 1)
    total = rows * per_row
    t_drain = drain_time_h(geometry, soil)
    if t_drain > max_drain_h:
        notes.append(f"Drain time {t_drain:.0f} h > {max_drain_h:.0f} h: low-permeability soil; "
                     "risk of prolonged ponding - consider shallower trenches or a different measure.")
        review = True
    return TrenchPlan(action, geometry, vi, hd, rows, per_row, total,
                      total_excavation_m3=total * geometry.volume_m3,
                      total_storage_m3=total * geometry.volume_m3,
                      drain_time_h=t_drain, notes=notes, requires_engineer_review=review)
